(function () {
  'use strict';
  let controller=null; let registrationTimer=null;
  const curriculum=window.UnikonCurriculum;
  const activityIds=Object.values(curriculum).flatMap((course)=>course.assessments.map((item)=>item.id));
  const answerIds=['',...new Set(Object.values(curriculum).flatMap((course)=>course.assessments.flatMap((item)=>Object.keys(item.choices))))];
  const emptySchema={type:'object',properties:{},additionalProperties:false};
  const result=(data,message)=>({content:[{type:'text',text:message}],structuredContent:data});
  function fail(error){const code=error&&error.code?error.code:'tool_failed';const message=error&&error.message?error.message:'The tool could not complete the request.';return{content:[{type:'text',text:`${code}: ${message}`}],structuredContent:{code,message},isError:true};}
  function validateEmpty(input){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw Object.assign(new Error('This tool does not accept parameters.'),{code:'invalid_parameters'});}
  function validateAnswer(input){const allowed=['activity_id','answer_id','reason'];if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).some((key)=>!allowed.includes(key)))throw Object.assign(new Error('Use only activity_id, answer_id, and reason.'),{code:'invalid_parameters'});if(!activityIds.includes(input.activity_id))throw Object.assign(new Error('Choose a listed activity_id.'),{code:'invalid_parameters'});if(input.answer_id!==undefined&&!answerIds.includes(input.answer_id))throw Object.assign(new Error('Choose a listed answer_id or omit it for written work.'),{code:'invalid_parameters'});if(typeof input.reason!=='string'||input.reason.trim().length<12||input.reason.trim().length>1200)throw Object.assign(new Error('Reason must contain 12 to 1200 characters.'),{code:'invalid_parameters'});return{activityId:input.activity_id,answerId:input.answer_id||'',reason:input.reason.trim()};}
  function definitions(app){return[
    {name:'get_learning_state',description:'Read the current course state and allowed next action before choosing a learning action.',inputSchema:emptySchema,annotations:{readOnlyHint:true},execute:async(input)=>{try{validateEmpty(input);const data=app.getState();if(!data)throw Object.assign(new Error('Open a course first.'),{code:'invalid_state'});return result(data,`Learning state loaded. Next: ${data.progress.next_step.label}`);}catch(error){return fail(error);}}},
    {name:'open_next_lesson',description:'Open the available lesson visibly. Repeated calls are safe.',inputSchema:emptySchema,annotations:{readOnlyHint:false},execute:async(input)=>{try{validateEmpty(input);const data=app.openLesson();return result(data,`Lesson opened visibly: ${data.lesson.title}`);}catch(error){return fail(error);}}},
    {name:'start_exercise',description:'Start the exercise after opening the lesson. Repeated calls are safe.',inputSchema:emptySchema,annotations:{readOnlyHint:false},execute:async(input)=>{try{validateEmpty(input);return result(app.startExercise(),'Exercise opened visibly.');}catch(error){return fail(error);}}},
    {name:'stage_exercise_answer',description:'Stage an answer only in the visible unlocked assessment for learner review. Never submit or save it.',inputSchema:{type:'object',properties:{activity_id:{type:'string',enum:activityIds},answer_id:{type:'string',enum:answerIds},reason:{type:'string',minLength:12,maxLength:1200}},required:['activity_id','reason'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input)=>{try{const answer=validateAnswer(input);return result(app.stageAnswer(answer.activityId,answer.answerId,answer.reason),'Answer staged; learner confirmation is required.');}catch(error){return fail(error);}}},
    {name:'get_progress_and_next_step',description:'Read completion, whether an answer is currently staged, and exactly one recommended next step.',inputSchema:emptySchema,annotations:{readOnlyHint:true},execute:async(input)=>{try{validateEmpty(input);const data=app.summary();if(!data)throw Object.assign(new Error('Open a course first.'),{code:'invalid_state'});const staging=data.staged_answer?` A response is staged for ${data.staged_activity_id}.`:' No response is currently staged.';return result(data,`${data.percent}% complete.${staging} Next: ${data.next_step.label}`);}catch(error){return fail(error);}}}
  ];}
  function cleanup(){if(registrationTimer){clearTimeout(registrationTimer);registrationTimer=null;}if(controller){controller.abort();controller=null;}}
  async function register(){cleanup();const root=document.querySelector('[data-uwmcp-app]');if(!root)return{supported:false,registered:[]};const status=root.querySelector('[data-agent-status]');const context=document.modelContext;if(!context||typeof context.registerTool!=='function'){status.lastChild.textContent='WebMCP unavailable; the learning interface still works normally.';return{supported:false,registered:[]};}controller=new AbortController();const localController=controller;const registered=[];try{for(const tool of definitions(window.UnikonLearningApp)){await context.registerTool(tool,{signal:localController.signal});if(localController.signal.aborted)return{supported:true,registered:[]};registered.push(tool.name);}status.classList.add('is-ready');status.lastChild.textContent='Five WebMCP learning tools are ready.';return{supported:true,registered};}catch(error){localController.abort();if(controller===localController)controller=null;status.lastChild.textContent='WebMCP registration was blocked; the interface still works normally.';return{supported:true,registered:[],error};}}
  function scheduleRegistration(){if(registrationTimer)clearTimeout(registrationTimer);registrationTimer=setTimeout(()=>{registrationTimer=null;register();},0);}
  document.addEventListener('unikon:view-change',(event)=>{if(event.detail&&event.detail.courseId)scheduleRegistration();else cleanup();});
  window.addEventListener('pagehide',cleanup,{once:true});
  window.UnikonWebMCPTools={activityIds,answerIds,definitions,validateEmpty,validateAnswer,register,cleanup};
  scheduleRegistration();
}());
