(function () {
  'use strict';
  let controller=null; let registrationTimer=null;
  const emptySchema={type:'object',properties:{},additionalProperties:false};
  const result=(data,message)=>({content:[{type:'text',text:message}],structuredContent:data});
  function fail(error){const code=error&&error.code?error.code:'tool_failed';const message=error&&error.message?error.message:'The tool could not complete the request.';return{content:[{type:'text',text:`${code}: ${message}`}],structuredContent:{code,message},isError:true};}
  function validateEmpty(input){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw Object.assign(new Error('This tool does not accept parameters.'),{code:'invalid_parameters'});}
  function definitions(app){return[
    {name:'get_learning_state',description:'Read the current course state and allowed next action before choosing a learning action.',inputSchema:emptySchema,annotations:{readOnlyHint:true},execute:async(input)=>{try{validateEmpty(input);const data=app.getState();if(!data)throw Object.assign(new Error('Open a course first.'),{code:'invalid_state'});return result(data,`Learning state loaded. Next: ${data.progress.next_step.label}`);}catch(error){return fail(error);}}},
    {name:'open_next_lesson',description:'Open the available lesson visibly. Repeated calls are safe.',inputSchema:emptySchema,annotations:{readOnlyHint:false},execute:async(input)=>{try{validateEmpty(input);const data=app.openLesson();return result(data,`Lesson opened visibly: ${data.lesson.title}`);}catch(error){return fail(error);}}},
    {name:'start_exercise',description:'Start the exercise after opening the lesson. Repeated calls are safe.',inputSchema:emptySchema,annotations:{readOnlyHint:false},execute:async(input)=>{try{validateEmpty(input);return result(app.startExercise(),'Exercise opened visibly.');}catch(error){return fail(error);}}},
    {name:'review_current_answer',description:'Review the learner-written answer in the visible unlocked assessment, identify what is strong or missing, and show formative feedback without submitting or saving it.',inputSchema:emptySchema,annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input)=>{try{validateEmpty(input);const data=app.reviewCurrentAnswer();return result(data,data.feedback);}catch(error){return fail(error);}}},
    {name:'get_progress_and_next_step',description:'Read completion and exactly one recommended next step.',inputSchema:emptySchema,annotations:{readOnlyHint:true},execute:async(input)=>{try{validateEmpty(input);const data=app.summary();if(!data)throw Object.assign(new Error('Open a course first.'),{code:'invalid_state'});return result(data,`${data.percent}% complete. Next: ${data.next_step.label}`);}catch(error){return fail(error);}}}
  ];}
  function cleanup(){if(registrationTimer){clearTimeout(registrationTimer);registrationTimer=null;}if(controller){controller.abort();controller=null;}}
  async function register(){cleanup();const root=document.querySelector('[data-uwmcp-app]');if(!root)return{supported:false,registered:[]};const status=root.querySelector('[data-agent-status]');const context=document.modelContext;if(!context||typeof context.registerTool!=='function'){status.lastChild.textContent='WebMCP unavailable; the learning interface still works normally.';return{supported:false,registered:[]};}controller=new AbortController();const localController=controller;const registered=[];try{for(const tool of definitions(window.UnikonLearningApp)){await context.registerTool(tool,{signal:localController.signal});if(localController.signal.aborted)return{supported:true,registered:[]};registered.push(tool.name);}status.classList.add('is-ready');status.lastChild.textContent='Five WebMCP learning tools are ready.';return{supported:true,registered};}catch(error){localController.abort();if(controller===localController)controller=null;status.lastChild.textContent='WebMCP registration was blocked; the interface still works normally.';return{supported:true,registered:[],error};}}
  function scheduleRegistration(){if(registrationTimer)clearTimeout(registrationTimer);registrationTimer=setTimeout(()=>{registrationTimer=null;register();},0);}
  document.addEventListener('unikon:view-change',(event)=>{if(event.detail&&event.detail.courseId)scheduleRegistration();else cleanup();});
  window.addEventListener('pagehide',cleanup,{once:true});
  window.UnikonWebMCPTools={definitions,validateEmpty,register,cleanup};
  scheduleRegistration();
}());
